# Generated by Django 4.0.4 on 2022-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
