# Generated by Django 4.0.4 on 2022-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='graphimage',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
