# Generated by Django 4.0.4 on 2022-05-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBSapp', '0002_graphimage_name_graphimage_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphImage',
        ),
    ]
